name: teneffus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^9.2.2
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_hooks: ^0.20.5
  fpdart: ^1.1.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hooks_riverpod: ^2.6.1
  riverpod: ^2.6.1
  email_validator: ^3.0.0
  riverpod_annotation: ^2.6.1
  cloud_firestore: ^5.6.0
  json_serializable: ^6.9.0
  lottie: ^3.3.0
  flutter_flip_card: ^0.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  riverpod_generator:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: false
  integrations:
    lottie: true
